import type { Metadata } from "next";

import { MainNav } from "@/components/main-nav";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

         <MainNav />
        {children}
     
    </html>
  );
}
